#server:
#  port: 8085
#  application:
#    name: CONFIG-SERVER
#  datasoures:
#    url: jdbc:mysql://localhost:3306/userservices
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
##  cloud:
##    config:
##      server:
##        git:
##          uri: https://github.com/DurgeshCoder/microservice-tutorial-config
##          clone-on-start: true
#
spring:
config:
  import: optional:configserver:http://localhost:8087

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default

