#server:
#  port: 8085
#spring:
#  application:
#    name: CONFIG-SERVER
#  datasoures:
#    url: jdbc:mysql://localhost:3306/userservices
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: update
##  cloud:
##    config:
##      server:
##        git:
##          uri: https://github.com/DurgeshCoder/microservice-tutorial-config
##          clone-on-start: true
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:  https://dev-77584981.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa7w65a24Px9Oyms5d7
            client-secret: JfsTTqODW21uapbbhKjW42sGzjcNs86GN7WL5dfU

        provider:
          okta:
            issuer-uri:  https://dev-77584981.okta.com/oauth2/default



#config:
#  import: optional:configserver:http://localhost:8087
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default










